### ISSUE TITLE
Over ride bed spawn setting, spawn on first join setting.

### ISSUE THREAD

**Issue by OneHungryPoboy** [Patrick260/Spawnpoint-Plugin#3]
**Is your feature request related to a problem? Please describe.**\
The current spawn on death setting, when true, overrides players spawning at their beds. The spawn on join setting places the player there every join.

**Describe the solution you'd like**\
An additional flag in the config that only spawns players at the setspawnpoint location on death if they do not have a bed. (OR a nether anchor, but I did not test this.) For spawn on join, a setting to only spawn there on first join.

**Describe alternatives you've considered**\

**Additional context**\
Looking for similar to vanilla spawning, where the player spawns at the specified setspawnpoint location when they first join, and if they die without a bed or anchor.

**Comment by Patrick260** [comment]
When you want a system which is similar to the vanilla one, then use the vanilla one...
